# Numpy Indexing and Conditionals

In [1]:
import numpy as np

In [2]:
arr_2d = np.array([[1,2,3,1], [4,5,6,5], [7,8,9,9], [4,7,3,3]])

In [3]:
arr_2d

array([[1, 2, 3, 1],
       [4, 5, 6, 5],
       [7, 8, 9, 9],
       [4, 7, 3, 3]])

In [4]:
arr_2d[2:,:]

array([[7, 8, 9, 9],
       [4, 7, 3, 3]])

In [5]:
arr = np.arange(10)
arr2 = np.arange(10) + 2

In [6]:
boolarr = arr > 4

In [17]:
arr[(arr < 3) & (arr > 8)]

array([], dtype=int32)

# Numpy Operations

In [8]:
arr + arr2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [12]:
arr2 / arr

C:\Users\VICTOR ANYADIOHA\AppData\Local\Temp\ipykernel_7820\2501189345.py:1: RuntimeWarning: divide by zero encountered in divide
  arr2 / arr


array([       inf, 3.        , 2.        , 1.66666667, 1.5       ,
       1.4       , 1.33333333, 1.28571429, 1.25      , 1.22222222])

In [14]:
arr2 ** arr

array([          1,           3,          16,         125,        1296,
             16807,      262144,     4782969,   100000000, -1937019605])

### Universal Array functions

In [18]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [19]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [20]:
np.log(arr)

C:\Users\VICTOR ANYADIOHA\AppData\Local\Temp\ipykernel_7820\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

### Numpy Exercise

In [21]:
# Array of 10 zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
# Array of 10 ones
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [23]:
# Array of 10 Fives
arr_fives = np.arange(10)
arr_fives[:] = 5
arr_fives

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [24]:
# array of integers from 10 to 50
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [25]:
# 3 X 3 matrix with values 0-8
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [26]:
# 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
# Random number b/w 0 and 1
np.random.rand(1)

array([0.79698841])

In [30]:
# 25 -random number array from a standard normal distribution
np.random.randn(25)

array([ 0.41775408,  0.02392923, -1.19316045,  0.68589542, -0.57986627,
        0.89216807, -0.20887662, -0.68421597, -0.35064543,  0.00169188,
       -0.44235589,  0.78264844, -0.06453007,  1.62051027,  1.54542392,
       -0.10139527, -0.53988221,  0.16362054,  0.07429664, -0.57527827,
        1.00065139,  0.43845749,  0.62582394, -1.06478965,  0.12122981])

In [31]:
# A array of 100 linearly spaced numbers  from 0.01 to 1
np.linspace(0.01, 1, 100)

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

In [32]:
# An array of 20 linearly spaced numbers b/w 0 and 1
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [34]:
# REFERENCE
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [35]:
# Display a block from 12 through 25
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [36]:
# Display 20
mat[3,4]

20

In [37]:
# Display block 2 to 12
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [38]:
# Display block 21 - 25 or row 5
mat[4]

array([21, 22, 23, 24, 25])

In [39]:
# Display a block from 16 through 25
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [40]:
# Sum of all values in mat
np.sum(mat)

325

In [42]:
# std deviation of all values in mat
np.std(mat)

7.211102550927978

In [47]:
# Sum of columns in mat
np.sum(mat, axis=0)

array([55, 60, 65, 70, 75])