# Welcome to the Numpy section

## Numpy Arrays

In [2]:
my_list = [1,2,3]

In [3]:
import numpy as np

In [4]:
array = np.array(my_list)

In [5]:
array

array([1, 2, 3])

In [6]:
my_mat = np.array([[1,2,3],[4,5,6],[7,8,9,10]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [ ]:
my_mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [ ]:
np.random.rand(5)

array([0.23882887, 0.35447766, 0.95353325, 0.77494073, 0.31048654])

In [ ]:
randarr = np.random.randint(0, 100, 10)

In [ ]:
randarr.reshape(2,5)

array([[65, 63,  5, 50, 45],
       [95, 93, 80, 43, 89]])

In [ ]:
randarr.argmax()

5

In [8]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])